[package]
name = "display_switch"
version = "0.2.0"
authors = ["Haim Gelfenbeyn <haim@g8n.me>"]
edition = "2018"

[build-dependencies]
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.48"

[dependencies]
config = "0.10.1"
dirs = "3.0.1"
serde = { version = "1.0.114", features = ["derive"] }
anyhow = "1.0.32"
log = "0.4.11"
simplelog = "0.8.0"
ddc = "0.2.2"
rusb = "0.6"

[target.'cfg(linux)'.dependencies]
ddc-hi = "0.1.3"
ddc-i2c = "0.2.1"
nvapi = "0.1.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser", "libloaderapi"] }
ddc-hi = "0.1.3"
ddc-winapi = "0.2.0"
